"""
This program performs minimal test of QUA program execution through IQCC cloud

- QUA program does not involve any signal input and output, decouple test from qubit, wiring, quam and qualibrate.
- config dictionary is strip down minimum to run simplest, so this script can run in stand-alone manner.
- Also you can use config dictionary generated by quam after checking minimal config works properly (use_quam = True)

If it runs properly, you will see output like:
```
    2025-08-29 19:09:31,513 - qm - INFO     - Starting session: 76a8329e-251f-47bf-8594-a1e1b196e079
    [19:09:34] QUA program submitted to qolab (id = 79ffc02a-388f-465e-9120-983903ac79d4)                                                             computers.py:426
            Execution started                                                                                                                      computers.py:446
    [19:09:37] Execution finished                                                                                                                     computers.py:460
    QUA program successfully executed
    👍     stdout:

    ⚛️      result
    {
    "r1": [[0.0],[0.5],[1.0]]
    }
    🕗 🐍  total Python execution time (s)
    2.586
    🕗 ⚛️   QUA execution time (s)
    1.230
```

"""

from iqcc_cloud_client import IQCC_Cloud
from qm import qua

# Minimum config
config = {
    "version": 1,
    "controllers": {"con1": {"type": "opx1000","fems": {
        1: {"type": "MW", "analog_outputs": {1: {"band": 2,"upconverters": {1: {"frequency": 5_000_000_000}}}}}}}}
    }

# Quam-generated config
use_quam = False
if use_quam:
    from quam_libs.components import QuAM
    machine = QuAM.load()
    config = machine.generate_config()

with qua.program() as qua_program:
    a = qua.declare(qua.fixed)
    r1 = qua.declare_stream()
    with qua.for_(a, 0, a < 1.1, a + 0.5):
        qua.save(a, r1)
    with qua.stream_processing():
        r1.save_all("r1")

qc = IQCC_Cloud(quantum_computer_backend="qolab")
run_data = qc.execute(qua_program, config, True, options = {"timeout":10})